name: "UmBox box upload"
description: "Automatically builds an UmBox Box and uploads it to the repo"
inputs:
  dir:
    description: "Directory containing the box.json"
    required: false
    default: "."
  secret:
    decription: "UmBox secret"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup UmBox
      shell: bash
      run: |
        cd ${{ inputs.dir }}
        sudo apt install -y curl unzip zip nsis rsync
        curl https://mrms.cz/dl/up/umbox_portable.zip -O
        unzip umbox_portable.zip
    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.dir }}
        ./umbox_portable/umbox build
    - name: Upload
      shell: bash
      run: |
        cd ${{ inputs.dir }}
        ./umbox_portable/umbox upload ${{ inputs.secret }} box.tar
