name: Upload workflow
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt install -y curl unzip zip nsis rsync
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Build and upload
      run: |
        cd ..
        curl -L https://github.com/marekmaskarinec/umbox/releases/download/v1.4/umbox_linux_v14.zip -o umbox_linux.zip
        unzip umbox_linux.zip
        cd umbox
        ../umbox_linux/umbox update
        LANG=C.UTF-8 make
        rsync umbox_portable.zip marek@mrms.cz:www/web/dl/umbox/
        rsync umbox_windows.zip marek@mrms.cz:www/web/dl/umbox/
        rsync umbox_linux.zip marek@mrms.cz:www/web/dl/umbox/
        rsync umbox_install.exe marek@mrms.cz:www/web/dl/umbox/
        rsync cmd/setup.sh marek@mrms.cz:www/web/dl/umbox/
